# Generated by Django 3.0.6 on 2020-08-22 08:58

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_porfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porfile',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porfile',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porfile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='porfile',
            name='instgram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='porfile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='porfile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='porfile',
            name='twtter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='porfile',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
