# Generated by Django 3.0.6 on 2020-08-22 10:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20200822_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='Profile_Cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/Profile-Cover'),
        ),
        migrations.AlterField(
            model_name='porfile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Phone Number'),
        ),
    ]
