# Generated by Django 3.0.6 on 2020-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20200822_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='Favorite',
            field=models.CharField(choices=[('Fun', 'Fun'), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Tv', 'Tv'), ('Books', 'Books'), ('Football', 'Football'), ('Challenge', 'Challenge')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
