# Generated by Django 3.0.6 on 2020-08-22 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0011_porfile_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='test',
            field=models.ManyToManyField(related_name='Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
