# Generated by Django 3.0.6 on 2020-08-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_porfile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfile',
            name='test',
        ),
    ]
