# Generated by Django 3.0.6 on 2020-08-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_auto_20200823_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/profile/'),
            preserve_default=False,
        ),
    ]
