# Generated by Django 3.0.6 on 2020-08-24 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0017_auto_20200824_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(null=True, upload_to='images/profile/')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twtter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instgram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('Profile_Cover', models.ImageField(null=True, upload_to='images/profile/Profile-Cover')),
                ('Favorite', models.CharField(choices=[('Fun', 'Fun'), ('Food', 'Food'), ('Travel', 'Travel'), ('Music', 'Music'), ('Swimming', 'Swimming'), ('Wrestling', 'Wrestling'), ('Tv', 'Tv'), ('Books', 'Books'), ('Football', 'Football'), ('Challenge', 'Challenge')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
