# Generated by Django 3.0.6 on 2020-08-24 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0018_auto_20200824_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfile',
            new_name='Profile',
        ),
    ]
