# Generated by Django 3.0.6 on 2020-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_auto_20200824_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_Cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/Profile-Cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
